
### AppControllerGetHello

@baseUrl = http://localhost:3000


### RecadosControllerFindAll
# @name RecadosControllerFindAll

GET {{baseUrl}}/recados/?limit=100&page=20

### RecadosControllerFindOne
# @name RecadosControllerFindOne

GET {{baseUrl}}/recados/2

### RecadosControllerFindOne
# @name RecadosControllerFindOne

POST  {{baseUrl}}/recados/
Content-Type: application/json

{
    "id": "Recado de teste",
    "descricao": "Descrição do recado de teste"
}
### RecadosControllerFindOne2
# @name RecadosControllerFindOne2

PATCH  {{baseUrl}}/recados/1/
Content-Type: application/json

{
    "descricao": "Descrição do recado de teste PATCH"
}
###
DELETE  {{baseUrl}}/recados/1/
Content-Type: application/json

{
    "descricao": "Descrição do recado de teste DELETE"
}